### ISSUE TITLE
Carthage?

### ISSUE THREAD

**Issue by zentrope** [scramjet/mpedn#1]
Aside: Any plans to make a Swift version?

I tried using this with Carthage

```
github "scramjet/mpedn" == 1.0.0
```

But got the following error:

```
Project "MPEdn.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at
 https://github.com/scramjet/mpedn/issues/new
```

Is this a (hopefully) easy fix to make, and are you interested in making it?

Here's the docs:

https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

I'm super new to the Xcode way of doing things, so I don't know if you can just create a framework target and have that work in this case. I'll give it a shot and see what happens.

**Comment by scramjet** [comment]
Hi, I've added a shared Xcode schema. I don't use Carthage, but that (and stable build tag) seems to be all that's needed. Let me know how it goes.

**Comment by zentrope** [comment]
Thanks! Yes, I tried it by modifying it by hand, here and get the following error when I run the app:

```
dyld: Library not loaded: @rpath/MPEdnParser.framework/MPEdnParser
  ...
  Reason: image not found
```

My app is brand new: no code. Works okay with the SwiftWebSockets framework. I dug around just a little and saw something (for Swift) where classes had to be marked public, but didn't go any further than that. I bet there's a whole lot of extra that has to be done, sadly.

**Comment by scramjet** [comment]
The only thing that comes to mind is: does Carthage require the library be built as a framework? MPEdn doesn't do so currently, and I don't know what's required (I do use it as framework in other projects, but that's automagically achieved via Cocoapod's `use_frameworks!` directive).

**Comment by zentrope** [comment]
I think it does require frameworks. I'll close this and maybe just use cocoapod.

**Comment by scramjet** [comment]
Yeah, sorry, I kind of thought that would be the problem.

I did have a brief look into the work required to make it a framework, and went eeek! and left it alone. It's a lot of extra moving parts, especially for iOS. And especially hard to justify the time for since Cocoapods (somehow) does it automagically.

**Comment by scramjet** [comment]
By the way, have you seen this? https://github.com/neonichu/Rome

**Comment by zentrope** [comment]
Didn't see it. Sounds like a good idea. I'm using MPEDN with cocoa pods at the moment. All the casting and extracting I have to do really underscores now nice Clojure is for this sort of thing. ;)

**Comment by scramjet** [comment]
Glad it's working out.

I'm doing as much as I can server-side in Clojure for the same reason :) Maybe Swift will be better.

**Comment by zentrope** [comment]
If you ever do tackle this for EDN, something like:
- https://github.com/owensd/json-swift/
- http://owensd.io/2014/06/21/json-parsing-take-two.html

would be great. I like how you can create a path-like structure to get nested details out.

**Comment by scramjet** [comment]
Looks like a nice API. Will certainly look at that as a model if/when I do convert to MPEdn Swift.
